### ISSUE TITLE
Query Recommendation by Recommendation Type

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#26]
**As a** User
**I need** the ability to query recommendation based on a attribute like type
**So that** I can filter the recommendations that has the given type. 

### Details & Assumptions: 
* ...

### Acceptance Criteria:

```gherkin
Given [a valid type]
When [the list API is called]
Then [Return all the recommendations which has the given filtered type value]
```

**Comment by Some1Somewhere** [comment]
@prasannachidire update the UserStory
