### ISSUE TITLE
Add Query Capability to the Model

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#27]
**As a** ...  
**I need** ...  
**So that** ...  

### Details & Assumptions: 
* ...

### Acceptance Criteria:

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by Some1Somewhere** [comment]
@prasannachidire I depend on this issue to create the endpoint to query recommendations for a product

**Comment by Some1Somewhere** [comment]
@prasannachidire need to write the User Story for this!
