### ISSUE TITLE
Add Query String Support to the List functions

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#28]
**As a** User
**I need** the ability to query recommendation based on a attribute like name, type
**So that** I can filter the recommendations that has the given attribute value. 

### Details & Assumptions: 
* 

### Acceptance Criteria:

```gherkin
Given [a valid filter type]
When [the list API is called]
Then [Return all the recommendations which has the given filtered attribute value]
```

**Comment by Some1Somewhere** [comment]
@prasannachidire I depend on this too for #32
