### ISSUE TITLE
Add a /health endpoint to the Recommendation service

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#35]
**As a** Developer  
**I need** ability an endpoint for health  
**So that** I can access the current health of the service
  

### Details & Assumptions: 
* The api should have /health as the path.
* The api should return 200 of the service is up and running, false otherwise.
* The api should return proper error message for incomplete request.

### Acceptance Criteria:

```gherkin
Given the recommendation service
When I access health of service as GET recommendations/health
Then it should return {"status":"OK}, 200 to be used as a health check for Kubernetes error otherwise.
```

**Comment by ekantikasingh0707** [comment]
@Some1Somewhere What do you think should be the estimate here?

**Comment by Some1Somewhere** [comment]
I would estimate 3 or 5

**Comment by ekantikasingh0707** [comment]
@Some1Somewhere Label will be enhancement no?

**Comment by Some1Somewhere** [comment]
Not entirely sure, it's not really beneficial to the end user, so I think it might be technical debt
