### ISSUE TITLE
Update devcontainer environment to download and install the IBM Cloud CLI 

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#37]
**As a** developer  
**I need** to update the configuration file inside our docker container 
**So that**  Kubernetes can be deployed on the IBM cluster according to our configuration metadata files

### Details & Assumptions: 
* deployment.yaml, service.yaml, secrets.yaml, postgres.yaml etc needs to be updated

### Acceptance Criteria:

```gherkin
Given the recommendation application when I try to 
When I try to access the app on the cluster
Then I am able to run and get the recommendations.
```

**Comment by Some1Somewhere** [comment]
I think this could be for the product owner and not just for the developer. Label and Estimates still missing
