### ISSUE TITLE
Deploy Service to Kubernetes Cluster

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#39]
As a developer
I need to set up cloud environment for the team
So that team can access the api in internet.

Details & Assumptions:
We are using IBM cloud for cloud 

```gherkin
Given an application
When it is ready to develop in the cloud 
Then it can be deployed and accessed by an IP address
```

**Comment by Some1Somewhere** [comment]
The Dev Environment is accessible through http://169.51.203.42:31001/
