### ISSUE TITLE
BDD for Update UI

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#56]
**As a** ...  user/business owner
**I need** ...  the UI to update a recommendation
**So that** ...  I can change a recommendation for a specific product

### Details & Assumptions: 
* The REST API of updating recommendations by products is fully devleoped

### Acceptance Criteria:

```gherkin
Given the UI
When I enter the product or id including the new recommendation to the input box
Then the recommendation is updated.
```

**Comment by Some1Somewhere** [comment]
This issue as well, needs to cover BDD of Updating the UI
