### ISSUE TITLE
BDD for Delete UI

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#57]
**As a**  user/business owner
**I need**  the UI to delete a recommendation
**So that**  I can delete recommendations for specific products that are not needed or incorrect,

### Details & Assumptions: 
* The REST API of deleting recommendations by products is fully developed

### Acceptance Criteria:

```gherkin
Given the UI
When I enter the product or id to the input box
Then the recommendation is deleted and a confirmation message is returned.
```

**Comment by Some1Somewhere** [comment]
@VickyZauner This issue needs to be modified to do the BDD for Delete UI
