### ISSUE TITLE
BDD for List API

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#58]
**As a** developer
**I need** BDD test of listing the recommendation
**So that**  developer can ensure it works as expected

### Details & Assumptions: 
* there will be a scenario in the feature file

### Acceptance Criteria:

```gherkin
Given [that the developer wants to see all the recommendations]
And there are three existing recommendations in the database
When [the developer lists the recommendations]
Then [all details of the four recommendations should be listed]
```

**Comment by Some1Somewhere** [comment]
@garyleelty I see this as part of your PR #70 . Could you confirm, reassign and mark this as completed
