### ISSUE TITLE
Create BDD .feature file and steps.py to test RESTful API

### ISSUE THREAD

**Issue by VickyZauner** [CSCI-GA-2820-FA22-001/recommendations#65]
**As a** Developer
**I need** a .feature file and steps file
**So that** I can configure the steps the code is going to do and test the RESTfule API from the outside

### Details & Assumptions: 
* write file

### Acceptance Criteria:

```gherkin
Given test case
When pull or merge the branch
Then we going to test on feature file
```

**Comment by Some1Somewhere** [comment]
@garyleelty Could you add estimates please?
